version: '3.8'

networks:
  test-network:
    driver: bridge

volumes:
  composer: {}
  redis_data: {}
  db-data: {}

services:

  nginx:
    build:
      context: ./docker/nginx
      args:
        PGID: "${PGID:-1006}"
        PUID: "${PUID:-1006}"
    depends_on:
      - php
    container_name: test-nginx
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./app:/var/www
      - ./app/var/log/nginx:/var/log/nginx:delegated
    ports:
      - "127.0.0.1:80:80"
    networks:
      - test-network

  php:
    build:
      context: ./docker/php
      args:
        PGID: "${PGID:-1006}"
        PUID: "${PUID:-1006}"
        DEVELOP: "true"
    container_name: test-php
    restart: unless-stopped
    volumes:
      - ./app:/var/www:rw
      - composer:/home/www-data/.composer:rw
    networks:
      - test-network

  database:
    image: mysql:latest
    container_name: test-db
    restart: unless-stopped
    tty: true
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - test-network
